### ISSUE TITLE
Movement Issue and potential fix?

### ISSUE THREAD

**Issue by OtisKP** [IllusiveBIair/Naruto-Evolution-Community#37]
The movement is really delayed? think it might be that you need to set the verb to instant so it doesn't queue up.

**Comment by douglasparker** [comment]
The verb is instant. The use of repeat macros does allow for future movements to be queued up, but that is taken care of by the movement delay.

We are aware of another minor issue with movement where in some cases your movement speed slows down temporarily. We are looking into this.

If this is not the issue that you are facing, please fill out the new bug report template so that we can reproduce this issue.

If you can record a small video or gif of the issue, we can use that to help identify whatever issue you are facing.

**Comment by IllusiveBIair** [comment]
Closing this issue for the time being as other movement bugs have been addressed and there's not enough information on this one to investigate.
